name: publish-ios-app
run-name: Publishing application to App Store Connect
on:
  push:
    tags:
      - "*" # Built on all releases
jobs:
  # You could also add your play store publish job here
  #publish-android:
  publish-ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Odevio/Odevio-CICD/github-actions/build-ios@v1.0.3
        with:
          api-key: ${{ secrets.ODEVIO_API_KEY }}
          app-key: 'N49N'
          build-type: publication